name: wrapdraw-ci
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint(py${{ matrix.python }})
    strategy:
      matrix:
        python:
          - 3.6
          - 3.7
          - 3.8

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install -r test-requirements.txt

      - name: Run syntax test
        run: tox -e `echo py${{ matrix.python }} | sed 's/\.//g'`

  image_build:
    runs-on: ubuntu-latest
    name: Build container image

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build container image
        run: "docker build . -t wrapdraw:latest"

  app_test:
    runs-on: ubuntu-latest
    name: App test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install ansible

      - name: Build container image
        run: "docker build . -t wrapdraw:latest"

      - name: Start wrapdraw image
        run: "docker run -itd --name wrapdraw wrapdraw:latest"

      - name: Download NW diagram with Ansible
        run: ansible-playbook main.yml
        working-directory: ./sample/ansible/
